config/routes.rb
JobInspector::Application.routes.draw do
 

  resources :tag_groups

  get "crawler/crawl_all"

  root to: 'static_pages#home'
  match '/static_pages/home', :to =>'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :hits

  resources :users 
  resources :feeds 

  resources :tags 

  resources :sessions, only: [:new, :create, :destroy]

end

app/models/feed.rb
class Feed < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, :use => :slugged

  attr_accessible :url, :name, :tag_group_id

  belongs_to :tag_group

  def to_param
		friendly_id
	end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all
    @user_from_params = User.find_by_username(params[:user_id])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feeds }
    end
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
    @feed = current_user.feeds.find_by_slug(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feed }
    end
  end

  # GET /feeds/new
  # GET /feeds/new.json
  def new
    @feed = Feed.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feed }
    end
  end

  # GET /feeds/1/edit
  def edit
    @feed = Feed.find(params[:id])
  end

  # POST /feeds
  # POST /feeds.json
  def create
    tag_group_id = params[:feed][:tag_group_id]
    @tag_group = TagGroup.find_by_id tag_group_id

    @feed = @tag_group.feeds.create(params[:feed])

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @tag_group, notice: 'Feed was successfully created.' }
        format.json { render json: @feed, status: :created, location: @feed }
      else
        format.html { render action: "new" }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /feeds/1
  # PUT /feeds/1.json
  def update
    @feed = Feed.find(params[:id])

    respond_to do |format|
      if @feed.update_attributes(params[:feed])
        format.html { redirect_to root_path, notice: 'Feed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed = Feed.find_by_slug(params[:id])
    @tag_group = TagGroup.find_by_slug(params[:tag_group])
    @feed.destroy

    respond_to do |format|
      format.html { redirect_to @tag_group }
      format.json { head :no_content }
    end
  end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.erb
<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Feed name' %><br />
    <%= f.text_field :name %><br />
    <%= f.label :url %><br />
    <%= f.text_field :url %>
    <%= f.hidden_field :tag_group_id, :value => @tag_group.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<h1>Listing feeds</h1>

<% if @user_from_params != current_user %>
  <h3> cant touch this </h3>
<% else %>
  <table>
    <tr>
      <th>Url</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    <% current_user.feeds.each do |feed| %>
    <tr>
      <td><%= feed.url %></td>
      <td><%= link_to 'Show', feed %></td>
      <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
      <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </table>
  <%= link_to 'New Feed', new_feed_path %>
<% end %>


<br />

app/views/feeds/new.html.erb
<h1>New feed</h1>

<%= render 'form' %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Feed:</b>
  <%= link_to @feed.name, @feed.url %>
</p>

<% if current_user != nil && current_user.feeds.find_by_id(@feed.id) %>
	<% if @feed && @feed.tags.any? %>
	  <b>Searching for following tags:</b><br>
		<% @feed.tags.each do |tag| %>
	  		<%= tag.value %> | <%= link_to 'delete', tag_path(tag, :feed_id => @feed.id), method: :delete %>
	  		<br>
		<% end %>
	<% end %>
<% end %>

<% @tag = @feed.tags.new() %>
<%= render :partial => '/tags/form', :locals => { :feed => @feed} %>

<br><br>

<% if @feed.hits.any? %>
Your hits:<br>
	<% @feed.hits.each do |hit| %>
		<%= link_to hit.title, hit.url %> <br>
	<% end%>
<% else %>
	No hits yet :(
<% end %>