config/routes.rb
JobInspector::Application.routes.draw do
 

  resources :tag_groups

  get "crawler/crawl_all"

  root to: 'static_pages#home'
  match '/static_pages/home', :to =>'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :hits

  resources :users 
  resources :feeds 

  resources :tags 

  resources :sessions, only: [:new, :create, :destroy]

end

app/models/tag_group.rb
class TagGroup < ActiveRecord::Base
	extend FriendlyId
  friendly_id :name, :use => :slugged

  attr_accessible :name, :user_id, :id

  belongs_to :user
  has_many :feeds, :dependent => :destroy
  has_many :tags, :dependent => :destroy
  has_many :hits, :dependent => :destroy

  def to_param
		friendly_id
	end
end

app/controllers/tag_groups_controller.rb
class TagGroupsController < ApplicationController
  # GET /tag_groups
  # GET /tag_groups.json
  def index
    @tag_groups = TagGroup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tag_groups }
    end
  end

  # GET /tag_groups/1
  # GET /tag_groups/1.json
  def show
    @tag_group = TagGroup.find_by_slug(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tag_group }
    end
  end

  # GET /tag_groups/new
  # GET /tag_groups/new.json
  def new
    @tag_group = TagGroup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tag_group }
    end
  end

  # GET /tag_groups/1/edit
  def edit
    @tag_group = TagGroup.find(params[:id])
  end

  # POST /tag_groups
  # POST /tag_groups.json
  def create

    @tag_group = current_user.tag_groups.new(params[:tag_group])

    respond_to do |format|
      if @tag_group.save
        format.html { redirect_to root_path, notice: 'Tag group was successfully created.' }
        format.json { render json: @tag_group, status: :created, location: @tag_group }
      else
        format.html { render action: "new" }
        format.json { render json: @tag_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tag_groups/1
  # PUT /tag_groups/1.json
  def update
    @tag_group = TagGroup.find(params[:id])

    respond_to do |format|
      if @tag_group.update_attributes(params[:tag_group])
        format.html { redirect_to @tag_group, notice: 'Tag group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tag_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tag_groups/1
  # DELETE /tag_groups/1.json
  def destroy
    @tag_group = TagGroup.find(params[:id])
    @tag_group.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tag_groups_helper.rb
module TagGroupsHelper
end

app/views/tag_groups/_form.html.erb
<%= form_for(@tag_group, :html => {:class => "group-add-form"}) do |f| %>
  <% if @tag_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag_group.errors.count, "error") %> prohibited this tag_group from being saved:</h2>

      <ul>
      <% @tag_group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name, :placeholder => "Name" %>
  </div>
  <div class="actions">
    <%= f.submit 'Save', :class => 'btn btn-small btn-block btn-primary'%>
  </div>
<% end %>

app/views/tag_groups/edit.html.erb
<h1>Editing tag_group</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag_group %> |
<%= link_to 'Back', tag_groups_path %>

app/views/tag_groups/index.html.erb
<h1>Listing tag_groups</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tag_groups.each do |tag_group| %>
  <tr>
    <td><%= tag_group.name %></td>
    <td><%= link_to 'Show', tag_group %></td>
    <td><%= link_to 'Edit', edit_tag_group_path(tag_group) %></td>
    <td><%= link_to 'Destroy', tag_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tag group', new_tag_group_path %>

app/views/tag_groups/new.html.erb
<h1>New tag_group</h1>

<%= render 'form' %>

<%= link_to 'Back', tag_groups_path %>

app/views/tag_groups/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
<div class="span4">
	<%= render :partial => '/tag_groups/sidebar' %>
</div>

<div id="span7">
		<% @tag_group = current_user.tag_groups.find(params[:id])  %>

		<% if @tag_group.feeds.any? %>
			<h2>Define your search</h2>
			<% @tag_group.feeds.each do |feed| %>
				<%= link_to feed.name, feed %> | <%= link_to 'delete', feed_path(feed, :tag_group => @tag_group.slug), method: :delete %> <br>
			<% end %>
		<% end %>

		<br> <h4>Add a feed for this group:</h4> 

		<% @feed = @tag_group.feeds.new() %>
		<%= render :partial => '/feeds/form', :locals => { :tag_group => @tag_group} %>

		<% if @tag_group.tags.any? %>
			<h2>Tags</h2>
			<% @tag_group.tags.each do |tag| %>
				<%= link_to tag.value, tag %> | <%= link_to 'delete', tag_path(tag, :tag_group => @tag_group.slug), method: :delete %> <br>
			<% end %>
		<% end %>

		<br>
		<h4>What will you be searching for?</h4> 
		<input name="tagsinput" class="tagsinput tagsinput-primary" value="Clean,Fresh,Modern,Unique" />
		<% @tag = @tag_group.tags.new() %>
		<%= render :partial => '/tags/form', :locals => { :tag_group => @tag_group} %>

		<% if @tag_group.hits.any? %>
		Your hits:<br>
			<% @tag_group.hits.each do |hit| %>
				<%= link_to hit.title, hit.url %> <br>
			<% end%>
		<% else %>
			No hits yet :(
		<% end %>
</div>
</div>