config/routes.rb
JobInspector::Application.routes.draw do
 

  resources :tag_groups

  get "crawler/crawl_all"

  root to: 'static_pages#home'
  match '/static_pages/home', :to =>'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :hits

  resources :users 
  resources :feeds 

  resources :tags 

  resources :sessions, only: [:new, :create, :destroy]

end

app/models/hit.rb
class Hit < ActiveRecord::Base
  attr_accessible :url, :title
  belongs_to :tag_group
end

app/controllers/hits_controller.rb
class HitsController < ApplicationController
  # GET /hits
  # GET /hits.json
  def index
    @hits = Hit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hits }
    end
  end

  # GET /hits/1
  # GET /hits/1.json
  def show
    @hit = Hit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hit }
    end
  end

  # GET /hits/new
  # GET /hits/new.json
  def new
    @hit = Hit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hit }
    end
  end

  # GET /hits/1/edit
  def edit
    @hit = Hit.find(params[:id])
  end

  # POST /hits
  # POST /hits.json
  def create
    @hit = Hit.new(params[:hit])

    respond_to do |format|
      if @hit.save
        format.html { redirect_to @hit, notice: 'Hit was successfully created.' }
        format.json { render json: @hit, status: :created, location: @hit }
      else
        format.html { render action: "new" }
        format.json { render json: @hit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hits/1
  # PUT /hits/1.json
  def update
    @hit = Hit.find(params[:id])

    respond_to do |format|
      if @hit.update_attributes(params[:hit])
        format.html { redirect_to @hit, notice: 'Hit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hits/1
  # DELETE /hits/1.json
  def destroy
    @hit = Hit.find(params[:id])
    @hit.destroy

    respond_to do |format|
      format.html { redirect_to hits_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/hits_helper.rb
module HitsHelper
end

app/views/hits/_form.html.erb
<%= form_for(@hit) do |f| %>
  <% if @hit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hit.errors.count, "error") %> prohibited this hit from being saved:</h2>

      <ul>
      <% @hit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hits/edit.html.erb
<h1>Editing hit</h1>

<%= render 'form' %>

<%= link_to 'Show', @hit %> |
<%= link_to 'Back', hits_path %>

app/views/hits/index.html.erb
<h1>Listing hits</h1>

<table>
  <tr>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hits.each do |hit| %>
  <tr>
    <td><%= hit.url %></td>
    <td><%= link_to 'Show', hit %></td>
    <td><%= link_to 'Edit', edit_hit_path(hit) %></td>
    <td><%= link_to 'Destroy', hit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Hit', new_hit_path %>

app/views/hits/new.html.erb
<h1>New hit</h1>

<%= render 'form' %>

<%= link_to 'Back', hits_path %>

app/views/hits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @hit.url %>
</p>


<%= link_to 'Edit', edit_hit_path(@hit) %> |
<%= link_to 'Back', hits_path %>